[project]
name = "stackmarket"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = []
[contracts.nft-trait]
path = "contracts/nft-trait.clar"
clarity_version = 1
analysis = { check_checker = { enabled = true, trusted_sender = false, trusted_caller = false, callee_filter = false }}

[contracts.mock-nft]
path = "contracts/mock-nft.clar"
clarity_version = 1
analysis = { check_checker = { enabled = true, trusted_sender = false, trusted_caller = false, callee_filter = false }}
depends_on = ["nft-trait"]

[contracts.nft-marketplace]
path = "contracts/nft-marketplace.clar"
clarity_version = 1
analysis = { check_checker = { enabled = true, trusted_sender = false, trusted_caller = false, callee_filter = false }}
depends_on = ["nft-trait"]

[repl]
clarity_version = 1
[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
trusted_sender = false
trusted_caller = false
callee_filter = false
